version: '2'

vars:
  NAME: vault-plugin-auth-openstack
  VERSION: 0.4.2

tasks:
  build:
    deps: [test]
    cmds:
      - CGO_ENABLED=0 go build .
  test:
    cmds:
      - go vet ./...
      - go test -v -coverprofile=cover.out ./...
  cover:
    deps: [test]
    cmds:
      - go tool cover -html=cover.out
  package:
    cmds:
      - GOOS={{.OS}} GOARCH={{.ARCH}} CGO_ENABLED=0 go build .
      - shasum -a 256 {{.NAME}} > sha256sum.txt
      - tar -czf release/{{.NAME}}_{{.OS}}_{{.ARCH}}.tar.gz {{.NAME}} sha256sum.txt
      - echo `cat sha256sum.txt` "({{.OS}}_{{.ARCH}})"
      - rm -rf {{.NAME}} sha256sum.txt
  release:
    deps: [test]
    cmds:
      - mkdir -p release
      - task: package
        vars: {OS: "linux", ARCH: "amd64"}
      - task: package
        vars: {OS: "linux", ARCH: "arm64"}
      - task: package
        vars: {OS: "linux", ARCH: "arm"}
      - task: package
        vars: {OS: "darwin", ARCH: "amd64"}
  github-release:
    deps: [release]
    cmds:
      - ghr v{{.VERSION}} release/
  clean:
    cmds:
      - rm -rf {{.NAME}} release cover.out
